# This is a basic workflow to help you get started with Actions

name: GITHUB-CICD-TESTING

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  # Allows you to run this workflow manually from the Actions tab
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Dev:
    runs-on: ubuntu-latest
    environment: 
      name: Development
    env:
      USERNAME: ${{ secrets.USERNAME }} 
      PASSWORD: ${{ secrets.PASSWORD }}
    # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build Mule Jar File
        run: mvn clean package -DskipMunitTests
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Deploy Mule Application
        run: mvn package deploy -DmuleDeploy -Dusername=${USERNAME} -Dpassword=${PASSWORD} -DapplicationName=mule-github-cicd-api-dev
