# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  # Allows you to run this workflow manually from the Actions tab
env: 
  username: "Suraj Sejwal"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Dev:
    
    runs-on: ubuntu-latest
    environment: 
      name: Development
    env:
      USERNAME: ${{ secrets.USERNAME }} 
    # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: read env variable
        run : echo Hello "$USERNAME"
  QA:
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    env:
      PASSWORD: ${{ secrets.PASSWORD }} 
    # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: read env variable
        run : echo Hello "$PASSWORD"
